version: '3.2'
services:
  web:
    image: jhaddock385/indusia-api:redis
    ports:
      - '17777:17777'
    depends_on:
      - redis
  redis:
    command:
      - redis-server
      - /usr/local/etc/redis/redis.config
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - type: bind
        source: ./redis.config
        target: /usr/local/etc/redis/redis.config
